#!/bin/bash

cd "$(dirname "$0")"

DOCKER="$(which docker)"
if [ $? != 0 ]; then
  echo "Please install docker cli"
  exit 1
fi

$DOCKER pull redis:3.0
$DOCKER ps -a --format {{.Names}} | grep redis_container >/dev/null && \
  container_exists=true
if [ $container_exists ]; then
  $DOCKER rm -f redis_container
fi
$DOCKER run --name redis_container -p 6379:6379 -v $(pwd)/data/redis:/data:rw \
  -d redis redis-server --appendonly yes
